name: Handle Dependabot Alerts
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Handle Dependabot Alerts
        run: |
          const github = require('@actions/github');
          const core = require('@actions/core');

          async function run() {
            try {
              const token = core.getInput('github-token');
              const octokit = github.getOctokit(token);
              const context = github.context;
              const owner = context.repo.owner;
              const repo = context.repo.repo;

              const { data: contributors } = await octokit.rest.repos.listContributors({
                owner,
                repo,
                per_page: 3
              });

              const assignees = contributors.map(contributor => contributor.login);

              const { data: alerts } = await octokit.rest.alerts.listAlertsForRepo({
                owner,
                repo,
              });

              alerts.forEach(async (alert) => {
                await octokit.rest.issues.create({
                  owner,
                  repo,
                  title: `Dependabot alert for ${alert.affected_package_name}`,
                  body: `Dependabot has raised an alert for ${alert.affected_package_name}.\n\n
                  - Affected version: ${alert.affected_range}\n
                  - Fixed version: ${alert.fixed_in}\n`,
                  assignees
                });
              });
            }
            catch (error) {
              core.setFailed(error.message);
            }
          }

          run();
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
